/**
 * Code generation for namespace injections.
 */

import type { TypeInfo } from "./transform.js";

/**
 * Generate TypeScript code that injects namespace declarations with
 * SchemaProvider implementations for each marked type.
 *
 * The generated code uses TypeScript's declaration merging feature:
 * a namespace with the same name as an interface/type merges with it,
 * allowing `TypeName.Schema` to be accessed directly.
 *
 * @param types - The types to generate namespaces for
 * @param schemas - Map from type name to JSON schema object
 * @returns TypeScript code to be appended to the source
 */
export function generateInjections(
  types: TypeInfo[],
  schemas: Map<string, object>
): string {
  if (types.length === 0) {
    return "";
  }

  const lines: string[] = [
    "",
    "// Auto-generated by @thinkwell/bun-plugin",
    'import type { SchemaProvider, JsonSchema } from "thinkwell:acp";',
    "",
  ];

  for (const { name } of types) {
    const schema = schemas.get(name);
    if (!schema) {
      continue;
    }

    const schemaJson = JSON.stringify(schema, null, 2)
      .split("\n")
      .map((line, i) => (i === 0 ? line : "      " + line))
      .join("\n");

    lines.push(
      `namespace ${name} {`,
      `  export const Schema: SchemaProvider<${name}> = {`,
      `    toJsonSchema: () => (${schemaJson}) as JsonSchema,`,
      `  };`,
      `}`,
      ""
    );
  }

  return lines.join("\n");
}
